version: "3.7" 
services:
  Rethium_Backend:
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/rethium
    env_file:
      - ./deployment/.env